version: '2'
services:
    roletest-app:
        image: roletest
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://roletest-mysql:3306/roletest?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://roletest-elasticsearch:9200
        ports:
            - 8080:8080
    roletest-mysql:
        extends:
            file: mysql.yml
            service: roletest-mysql
    roletest-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: roletest-elasticsearch
